[[main]]
name = "About"
url = "/about"
identifier = "soIZA0asbA"
weight = 1

[[main]]
name = "Posts"
pageRef = "posts"
identifier = "ZIxgIcoXld"
weight = 2


[[main]]
name = "Sjov"
url = "https://3sem.kursusmaterialer.dk/"
pageRef = "ballade"
identifier = "ZIxgIcoXlx"
weight = 3

[[footer]]
none = "none"
